sudo: false
language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=standard
env:
  - TEST_SUITE=coverage
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
